src/main/java/cn/nukkit/permission/DefaultPermissions.java

nukkit.broadcast.*** must inside nukkit.broadcast

Fixed a wrong permission branch name.

---

src/main/java/cn/nukkit/entity/Effect.java

I will implement effects for effects later.

Added more effects (hunger is not working)

---

src/main/java/cn/nukkit/network/protocol/MovePlayerPacket.java

Maybe some issue from upstream project.

Implements MovePlayerPacket

---

src/main/java/cn/nukkit/network/protocol/AddPaintingPacket.java
src/main/java/cn/nukkit/network/protocol/RemoveBlockPacket.java

Implements AddPaintingPacket and RemoveBlockPacket

---

src/main/java/cn/nukkit/Server.java
src/main/java/cn/nukkit/network/Network.java
src/main/java/cn/nukkit/network/RakNetInterface.java
src/main/java/cn/nukkit/network/protocol/DataPacket.java
src/main/java/cn/nukkit/utils/BinaryStream.java

All methods and fields access have been corrected.

Make DataPacket extend BinaryStream

---

src/main/java/cn/nukkit/entity/Attribute.java
src/main/java/cn/nukkit/network/protocol/DataPacket.java
src/main/java/cn/nukkit/network/protocol/ExplodePacket.java
src/main/java/cn/nukkit/network/protocol/UpdateAttributesPacket.java
src/main/java/cn/nukkit/network/protocol/UseItemPacket.java

Implements some packets

---

src/main/java/cn/nukkit/entity/Arrow.java
src/main/java/cn/nukkit/entity/Entity.java
src/main/java/cn/nukkit/entity/FallingSand.java
src/main/java/cn/nukkit/entity/Human.java
src/main/java/cn/nukkit/event/entity/EntityBlockChangeEvent.java

Impl FallingSand and a typo fix

---

src/main/java/cn/nukkit/entity/Explosive.java
src/main/java/cn/nukkit/entity/PrimedTNT.java
src/main/java/cn/nukkit/event/entity/EntityExplosionPrimeEvent.java
src/main/java/cn/nukkit/level/Explosion.java

Impl PrimedTNT

---

src/main/java/cn/nukkit/Player.java

Added Movement Speed support

---

src/main/java/cn/nukkit/Nukkit.java

ASCII art logo

---

nukkit.yml

Nukkit can't create this file when nukkit.yml not exists in jar, so I added it.

fixed server crash when missing nukkit.yml

---

src/main/java/cn/nukkit/block/Block.java
src/main/java/cn/nukkit/block/DoublePlant.java
src/main/java/cn/nukkit/block/FenceGate.java
src/main/java/cn/nukkit/block/FenceGateAcacia.java
src/main/java/cn/nukkit/block/FenceGateBirch.java
src/main/java/cn/nukkit/block/FenceGateDarkOak.java
src/main/java/cn/nukkit/block/FenceGateJungle.java
src/main/java/cn/nukkit/block/FenceGateSpruce.java
src/main/java/cn/nukkit/block/Flower.java
src/main/java/cn/nukkit/item/Item.java

Flowers and FenceGates

---

src/main/java/cn/nukkit/Player.java
src/main/java/cn/nukkit/block/Bedrock.java
src/main/java/cn/nukkit/block/Cobblestone.java
src/main/java/cn/nukkit/block/Grass.java
src/main/java/cn/nukkit/block/Leaves.java
src/main/java/cn/nukkit/block/Sapling.java

fixed a small bug and added some blocks

fixed a small bug and added some blocks

---

src/main/java/cn/nukkit/Player.java
src/main/java/cn/nukkit/block/Air.java
src/main/java/cn/nukkit/block/Block.java
src/main/java/cn/nukkit/block/Coal.java
src/main/java/cn/nukkit/block/DiamondOre.java
src/main/java/cn/nukkit/block/Dirt.java
src/main/java/cn/nukkit/block/Fire.java
src/main/java/cn/nukkit/block/GoldOre.java
src/main/java/cn/nukkit/block/Grass.java
src/main/java/cn/nukkit/block/GrassPath.java
src/main/java/cn/nukkit/block/Gravel.java
src/main/java/cn/nukkit/block/HardenedClay.java
src/main/java/cn/nukkit/block/Ice.java
src/main/java/cn/nukkit/block/IronOre.java
src/main/java/cn/nukkit/block/LapisOre.java
src/main/java/cn/nukkit/block/Podzol.java
src/main/java/cn/nukkit/block/RedstoneOre.java
src/main/java/cn/nukkit/block/Sponge.java
src/main/java/cn/nukkit/block/StillLava.java
src/main/java/cn/nukkit/block/StillWater.java

fixed IllegalArgumentException when player's health < 0

fixed IllegalArgumentException when player's health < 0

---

src/main/java/cn/nukkit/block/Block.java
src/main/java/cn/nukkit/block/DoubleSlab.java
src/main/java/cn/nukkit/block/Glass.java
src/main/java/cn/nukkit/block/Gold.java
src/main/java/cn/nukkit/block/Iron.java
src/main/java/cn/nukkit/block/Lapis.java

To be honest, this is a bug that I fixed...

added glass to creative inventory

---

src/main/java/cn/nukkit/entity/data/StringEntityData.java

Add toString() method into StringEntityData.java.

Try fix #84

---

src/main/java/cn/nukkit/utils/Config.java
src/main/java/cn/nukkit/utils/TextFormat.java

Now plugin develoers will be able to use TextFormat.colorize ("&cred text &gold text");

"colorize" method for TextFormat

---

src/main/java/cn/nukkit/Player.java
src/main/java/cn/nukkit/block/Block.java
src/main/java/cn/nukkit/block/BurningFurnace.java
src/main/java/cn/nukkit/block/Furnace.java
src/main/java/cn/nukkit/inventory/ContainerInventory.java
src/main/java/cn/nukkit/level/format/generic/BaseFullChunk.java
src/main/java/cn/nukkit/nbt/tag/CompoundTag.java
src/main/java/cn/nukkit/tile/Furnace.java
src/main/java/cn/nukkit/tile/Tile.java

furace are buggy, may cause damage to your level. so do not use that yet

fixed tiles, added furnace, but DO NOT USE yet !

---

src/main/java/cn/nukkit/scheduler/ServerScheduler.java
src/test/java/cn/nukkit/scheduler/ServerSchedulerTest.java

To fix #158

---

src/main/java/cn/nukkit/command/SimpleCommandMap.java
src/main/java/cn/nukkit/command/defaults/SetWorldSpawnCommand.java
src/main/java/cn/nukkit/command/defaults/SpawnpointCommand.java

/spawnpoint and /setworldspawn

Impl some commands

---

src/main/java/cn/nukkit/Player.java
src/main/java/cn/nukkit/level/sound/ButtonClickSound.java
src/main/java/cn/nukkit/level/sound/NoteBoxSound.java
src/main/java/cn/nukkit/network/protocol/LevelEventPacket.java

Rename ButtonClickSound, add real NoteBoxSound, fix player food level when respawn

Rename ButtonClickSound, add real NoteBoxSound, fix player food level

---

src/main/java/cn/nukkit/command/defaults/BanIpCommand.java

Removed not needed line from the language file

banip.invalid update

---

src/main/java/cn/nukkit/utils/TextFormat.java

Added TextFormat.getLastColors method to determine last color used in String

Added TextFormat.getLastColors method 

---

src/main/java/cn/nukkit/Player.java
src/main/java/cn/nukkit/Server.java
src/main/java/cn/nukkit/block/Block.java
src/main/java/cn/nukkit/block/BrewingStand.java
src/main/java/cn/nukkit/inventory/BrewingInventory.java
src/main/java/cn/nukkit/inventory/BrewingRecipe.java
src/main/java/cn/nukkit/inventory/CraftingManager.java
src/main/java/cn/nukkit/item/BrewingStand.java
src/main/java/cn/nukkit/item/GlassBottle.java
src/main/java/cn/nukkit/item/Item.java
src/main/java/cn/nukkit/item/Potion.java
src/main/java/cn/nukkit/tile/BrewingStand.java

I have tested it on pocketmine and worked so i hope it will be there too

Add brewing stand

---

src/main/java/cn/nukkit/Player.java
src/main/java/cn/nukkit/event/player/PlayerChatEvent.java
src/main/java/cn/nukkit/event/player/PlayerCommandPreprocessEvent.java
src/main/java/cn/nukkit/event/player/PlayerMessageEvent.java

Chat is chat, Command is command.

Something on #197 (chat and command)

---

src/main/java/cn/nukkit/plugin/Plugin.java
src/main/java/cn/nukkit/plugin/PluginBase.java

More argument check. And prevent create file out of data folder.

Change Plugin.saveResource()

---

src/main/java/cn/nukkit/Player.java
src/main/java/cn/nukkit/Server.java
src/main/java/cn/nukkit/block/Block.java
src/main/java/cn/nukkit/block/CoalOre.java
src/main/java/cn/nukkit/block/DiamondOre.java
src/main/java/cn/nukkit/block/GlowingRedstoneOre.java
src/main/java/cn/nukkit/block/LapisOre.java
src/main/java/cn/nukkit/block/QuartzOre.java
src/main/java/cn/nukkit/block/RedstoneOre.java
src/main/java/cn/nukkit/entity/ExpBottleThrown.java
src/main/java/cn/nukkit/entity/ExpOrb.java
src/main/java/cn/nukkit/entity/ThrownExpBottle.java
src/main/java/cn/nukkit/entity/ThrownPotion.java
src/main/java/cn/nukkit/entity/XPOrb.java
src/main/java/cn/nukkit/item/ExpBottle.java
src/main/java/cn/nukkit/item/Item.java
src/main/java/cn/nukkit/item/SplashPotion.java
src/main/java/cn/nukkit/level/Level.java
src/main/java/cn/nukkit/level/particle/GenericParticle.java
src/main/java/cn/nukkit/level/particle/SpellParticle.java

For potions, It seems like potion system requires food system done. So I'll do this PR only in exp and exp bottles.

Exp and Exp bottles (ABLE TO MERGE)

---

src/main/java/cn/nukkit/Server.java

To fix #276

---

src/main/java/cn/nukkit/block/Quartz.java

Fixed block place Quartz

---

src/main/java/cn/nukkit/command/defaults/TeleportCommand.java

Fixed /tp Exception

---

src/main/java/cn/nukkit/block/Block.java
src/main/java/cn/nukkit/block/Mycelium.java

Please check this, I'm not sure in BLOCK_UPADTE

implementation Mycelium

---

src/main/java/cn/nukkit/command/defaults/TeleportCommand.java

[INFO]Teleported <player> to  (172.12456413215865323,81.8645348631745615665,196.97413287865446553)
=>[INFO]Teleported <player> to (172.1245,81.8645,196.9741)

Format the Coordinate of teleporting

---

src/main/java/cn/nukkit/command/SimpleCommandMap.java

Fix concurrent modification exception

---

src/main/java/cn/nukkit/block/Block.java
src/main/java/cn/nukkit/block/RedstoneWire.java

small fix #216

---

src/main/java/cn/nukkit/block/Air.java
src/main/java/cn/nukkit/block/Bed.java
src/main/java/cn/nukkit/block/Cobblestone.java
src/main/java/cn/nukkit/block/DeadBush.java
src/main/java/cn/nukkit/block/Diamond.java
src/main/java/cn/nukkit/block/DiamondOre.java
src/main/java/cn/nukkit/block/Dirt.java
src/main/java/cn/nukkit/block/DoubleWoodSlab.java
src/main/java/cn/nukkit/block/Emerald.java
src/main/java/cn/nukkit/block/EmeraldOre.java
src/main/java/cn/nukkit/block/EndStone.java
src/main/java/cn/nukkit/block/Farmland.java
src/main/java/cn/nukkit/block/Fence.java
src/main/java/cn/nukkit/block/FenceGate.java
src/main/java/cn/nukkit/block/Glass.java
src/main/java/cn/nukkit/block/GlassPane.java
src/main/java/cn/nukkit/block/GlowingObsidian.java
src/main/java/cn/nukkit/block/Glowstone.java
src/main/java/cn/nukkit/block/Gold.java
src/main/java/cn/nukkit/block/GoldOre.java

All information was taken from http://minecraft.gamepedia.com/

Update blocks 

---

src/main/java/cn/nukkit/Player.java
src/main/java/cn/nukkit/entity/Entity.java
src/main/java/cn/nukkit/entity/Human.java
src/main/java/cn/nukkit/item/Item.java
src/main/java/cn/nukkit/level/format/anvil/Chunk.java
src/main/java/cn/nukkit/nbt/tag/CompoundTag.java
src/main/java/cn/nukkit/tile/BrewingStand.java
src/main/java/cn/nukkit/tile/Chest.java
src/main/java/cn/nukkit/tile/Furnace.java

之前的代码泛型传递用新对象。代价太高了，直接改成传Class比较好。

Fix TagList.getList(String, T)

---

src/main/java/cn/nukkit/nbt/NBTIO.java

Use Java's atomic func to provide fully safe write

---

src/main/java/cn/nukkit/block/Block.java
src/main/java/cn/nukkit/command/defaults/SetWorldSpawnCommand.java
src/main/java/cn/nukkit/command/defaults/SpawnpointCommand.java
src/main/java/cn/nukkit/command/defaults/TeleportCommand.java

Round = 2, because 4 is too many and on small screens is 2-3 lines when teleporting the player from one place to another
You also need to accept the update language
https://github.com/Nukkit/Languages/pull/14

Small update commands

---

src/main/java/cn/nukkit/entity/Effect.java

Speed and Slowness :D

---

src/main/java/cn/nukkit/level/Location.java
src/main/java/cn/nukkit/level/Position.java

Fix Location and position methods will return Location and Positions :) …
Added getLevelBlock() method  to Position

Minor additions to Location and Position classes: it will be useful

---

src/main/java/cn/nukkit/Server.java

When you defining in nukkit.yml new worlds without additional presets (and seeds) you'll get an exception and server will not start.
Now this issue is fixed :)

Fix of #415

---

src/main/java/cn/nukkit/block/SnowBlock.java

Fixed bugs related to SnowBlock

---

src/main/java/cn/nukkit/Server.java
src/main/java/cn/nukkit/block/Block.java
src/main/java/cn/nukkit/block/BlockSignPost.java
src/main/java/cn/nukkit/block/BlockSkull.java
src/main/java/cn/nukkit/blockentity/BlockEntitySkull.java
src/main/java/cn/nukkit/item/Item.java
src/main/java/cn/nukkit/item/ItemSkull.java
src/main/java/cn/nukkit/level/Level.java

Skulls. NOT FINISHED
Thanks for @chaunhan

[DONE] Impl skulls

---

src/main/java/cn/nukkit/Server.java
src/main/java/cn/nukkit/block/BlockFlowerPot.java
src/main/java/cn/nukkit/block/BlockSkull.java
src/main/java/cn/nukkit/blockentity/BlockEntity.java
src/main/java/cn/nukkit/blockentity/BlockEntityBrewingStand.java
src/main/java/cn/nukkit/blockentity/BlockEntityChest.java
src/main/java/cn/nukkit/blockentity/BlockEntityEnchantTable.java
src/main/java/cn/nukkit/blockentity/BlockEntityFlowerPot.java
src/main/java/cn/nukkit/blockentity/BlockEntityFurnace.java
src/main/java/cn/nukkit/blockentity/BlockEntitySign.java
src/main/java/cn/nukkit/blockentity/BlockEntitySkull.java
src/main/java/cn/nukkit/blockentity/BlockEntitySpawnable.java
src/main/java/cn/nukkit/item/Item.java
src/main/java/cn/nukkit/item/ItemFlowerPot.java
src/main/java/cn/nukkit/level/Level.java

1. Implement flower pots
2. Garbage block entity check during /gc command
NOT FINISHED
TODO: Fix a bug, that if put anything into a flower pot, it didn't update in time. Maybe client-side bug.

[WIP] Impl Flower Pots

---

src/main/java/cn/nukkit/Player.java

STILL IN PROGRESS, DO NOT MERGE

[WIP] Enhanced Locale API

---

src/main/java/cn/nukkit/utils/Config.java

I think it was private by mistake

Make getStringList public

---

src/main/java/cn/nukkit/utils/Config.java
src/main/java/cn/nukkit/utils/SimpleConfig.java

1. Fix problems about final
2. Implemention of SimpleConfig in inner classes and lambdas now tested OK

Small fix on SimpleConfig

---

src/main/java/cn/nukkit/level/generator/Generator.java
src/main/java/cn/nukkit/level/generator/Normal.java
src/main/java/cn/nukkit/level/generator/populator/PopulatorCaves.java

1.Fix Perlin3D Noise
2.Caves! Although it's still working in progress.
3.Riverbed more "randomly"
4.Small fix on mountains.

more on generator

---

src/main/java/cn/nukkit/Player.java

Fixes a bug with the slots

---

src/main/java/cn/nukkit/inventory/PlayerInventory.java

To fix #518

---

src/main/java/cn/nukkit/Player.java

Fix drop item bug: very bad for W10 edition.

Fix drop item bug

---

src/main/java/cn/nukkit/block/BlockLava.java
src/main/java/cn/nukkit/block/BlockLiquid.java
src/main/java/cn/nukkit/block/BlockWater.java

tickRate() already in BlockLiquid!

Small fix tickRate()

---

src/main/java/cn/nukkit/Player.java
src/main/java/cn/nukkit/Server.java
src/main/java/cn/nukkit/entity/weather/EntityLightning.java
src/main/java/cn/nukkit/entity/weather/EntityLightningStrike.java
src/main/java/cn/nukkit/entity/weather/EntityWeather.java
src/main/java/cn/nukkit/event/entity/EntityDamageEvent.java
src/main/java/cn/nukkit/event/weather/LightningStrikeEvent.java
src/main/java/cn/nukkit/level/Level.java

Fix time sending bugs.. Add level.canSeeSky(Vector3) API,
Added Lightning! And now the thunder weather is working!
Players' fire will be extinguished by the rain!

Fix time sending bugs.. Add level.canSeeSky(Vector3) API, Added lightning!

---

src/main/java/cn/nukkit/entity/weather/EntityLightning.java
src/main/java/cn/nukkit/level/Level.java

Lightning makes the Creeper on Power!
Small fix of lightning spawn.

Lightning makes the Creeper on Power! Small fix of lightning spawn.

---

src/main/java/cn/nukkit/level/generator/biome/ForestBiome.java

Change birch forest ID to support generic forest.

Fix oak forest trees not generating.

---

src/main/java/cn/nukkit/level/generator/biome/ForestBiome.java
src/main/java/cn/nukkit/level/generator/biome/PlainBiome.java
src/main/java/cn/nukkit/level/generator/biome/SandyBiome.java
src/main/java/cn/nukkit/level/generator/biome/SwampBiome.java
src/main/java/cn/nukkit/level/generator/populator/PopulatorCactus.java
src/main/java/cn/nukkit/level/generator/populator/PopulatorDeadBush.java
src/main/java/cn/nukkit/level/generator/populator/PopulatorFlower.java
src/main/java/cn/nukkit/level/generator/populator/PopulatorLilyPad.java
src/main/java/cn/nukkit/level/generator/populator/PopulatorMineshaft.java

Added dead bush to desert biome.
Added cacti to desert biome.
Added trees and blue orchid to the swamp biome.
Added new flowers to plain biome.
Added lily pad to the swamp biome.
Compiled and tested and it works.

Generator improvements and lots more features

---

src/main/java/cn/nukkit/command/defaults/WeatherCommand.java
src/main/java/cn/nukkit/entity/Entity.java

Fixed when lightning struck after use /weather clear

fix weather

---

src/main/java/cn/nukkit/inventory/CraftingManager.java

Craft fixes.

---

src/main/java/cn/nukkit/item/ItemTool.java

It's already there... It does not fix. https://github.com/Nukkit/Nukkit/blob/e6df291f518b06e3e59b78c950d03edec41f54a2/src/main/java/cn/nukkit/Player.java#L2478-L2484

Removed repeated code

---

src/main/java/cn/nukkit/Player.java
src/main/java/cn/nukkit/block/BlockFire.java
src/main/java/cn/nukkit/entity/Entity.java

Player in creative mode should not be ignited!

fix extinguish the player in creative

---

src/main/java/cn/nukkit/redstone/Redstone.java

just an enhancement, better coding practices

remove duplicated code, replace with for loop

---

src/main/java/cn/nukkit/Player.java
src/main/java/cn/nukkit/PlayerFood.java
src/main/java/cn/nukkit/block/BlockCactus.java
src/main/java/cn/nukkit/block/BlockFire.java
src/main/java/cn/nukkit/block/BlockLava.java
src/main/java/cn/nukkit/entity/Entity.java
src/main/java/cn/nukkit/entity/EntityLiving.java
src/main/java/cn/nukkit/entity/item/EntityBoat.java
src/main/java/cn/nukkit/entity/item/EntityFallingBlock.java
src/main/java/cn/nukkit/entity/item/EntityItem.java
src/main/java/cn/nukkit/entity/item/EntityMinecartEmpty.java
src/main/java/cn/nukkit/entity/item/EntityPrimedTNT.java
src/main/java/cn/nukkit/entity/item/EntityXPOrb.java
src/main/java/cn/nukkit/entity/projectile/EntityProjectile.java
src/main/java/cn/nukkit/entity/weather/EntityLightning.java
src/main/java/cn/nukkit/level/Explosion.java
src/main/java/cn/nukkit/potion/Effect.java
src/main/java/cn/nukkit/potion/Potion.java

Revert "Fix attack. Now the player pushes and he gets true damage."

---

src/main/java/cn/nukkit/utils/Config.java
src/main/java/cn/nukkit/utils/SimpleConfig.java

Added Skip annotation that will allow to prevent saving and/or loading of fields defined by this annotation.

Simple SimpleConfig modification

---

src/main/java/cn/nukkit/utils/Config.java

Added method Config.load (Inputstream is) required to load config values (for example init, values) directly from plugin's jar file.
Example:
```
String language = "rus";
Config lng = new Config(language+".lng",Config.YAML);
InputStream is = plugin.getClass().getResourceAsStream("/lang/"+language+".lng");
lng.load(is); // load rus.lng from plugin's jar.
```

Added Config.load (Inputstream is)

---

src/main/java/cn/nukkit/level/Level.java

The player also gets experience in creative and adventure

Fixed pick up experience

---

src/main/java/cn/nukkit/utils/SimpleConfig.java

Made fields accessible (required to use private variables with setters/gettes)

SimpleConfiX

---

src/main/java/cn/nukkit/command/defaults/KillCommand.java

Improvement /kill command

---

src/main/java/cn/nukkit/Player.java

if there were two maps but both have the same Level Name. And then, you know.

Fixed if there were two maps but both have the same Level Name. And then, you know.

---

src/main/java/cn/nukkit/level/Level.java

- fix experience 
- removed unnecessary code

Experience should fall only players and in survival mode.

---

src/main/java/cn/nukkit/block/Block.java
src/main/java/cn/nukkit/block/BlockLitRedstoneLamp.java
src/main/java/cn/nukkit/block/BlockRedstone.java
src/main/java/cn/nukkit/block/BlockRedstoneLamp.java
src/main/java/cn/nukkit/block/BlockRedstoneTorch.java
src/main/java/cn/nukkit/block/BlockRedstoneWire.java
src/main/java/cn/nukkit/block/BlockTNT.java

- Removed unnecessary code
- Dynamite now explodes from the signal of red dust
- Redstone block now generates a signal
- LitRedstoneLamp now works :)
- Fixed a bug with the update signal. Thanks @Angelic47

Redstone update :D

---

src/main/java/cn/nukkit/block/BlockRedstone.java
src/main/java/cn/nukkit/level/Level.java
src/main/java/cn/nukkit/redstone/Redstone.java

Redstone block now working, hmmmm :3

some fix with redstone

---

src/main/java/cn/nukkit/item/ItemFlintSteel.java

Added creation of a portal to hell

---

src/main/java/cn/nukkit/Server.java
src/main/java/cn/nukkit/entity/EntityOwnable.java
src/main/java/cn/nukkit/entity/passive/EntityAnimal.java
src/main/java/cn/nukkit/entity/passive/EntityChicken.java
src/main/java/cn/nukkit/entity/passive/EntityCow.java
src/main/java/cn/nukkit/entity/passive/EntityOcelot.java
src/main/java/cn/nukkit/entity/passive/EntityPig.java
src/main/java/cn/nukkit/entity/passive/EntityRabbit.java
src/main/java/cn/nukkit/entity/passive/EntitySheep.java
src/main/java/cn/nukkit/entity/passive/EntityTameable.java
src/main/java/cn/nukkit/entity/passive/EntityWolf.java
src/main/java/cn/nukkit/item/Item.java

I added:
1. spawn eggs for all defined passive mobs
2. EntityAnimal.spawnTo() to allow the passive entities to spawn
3. Rabbit & Ocelot
4. Fixed typo in EntityChicken.getDrops().

Squashed merge of changes from #446

---

src/main/java/cn/nukkit/item/ItemBootsLeather.java
src/main/java/cn/nukkit/item/ItemChestplateLeather.java
src/main/java/cn/nukkit/item/ItemColorArmor.java
src/main/java/cn/nukkit/item/ItemHelmetLeather.java
src/main/java/cn/nukkit/item/ItemLeggingsLeather.java
src/main/java/cn/nukkit/nbt/tag/CompoundTag.java

- Added setColor methods to change color of Lether Item
- Added getColor to detect color of Leather Item
- Added exists method to CompoundTag to check existence of NBT tag

Colorized leather armor :)

---

src/main/java/cn/nukkit/Server.java
src/main/java/cn/nukkit/utils/Config.java
src/main/java/cn/nukkit/utils/ConfigSection.java

1. Added ConfigSection as base of Config class. 
2. Added constructors, that allows to create Config instance that not bounded to any file.
3. Added methods: getSection, getSections, getKeys to improve config usability

Config modification:

---

src/main/java/cn/nukkit/level/generator/biome/OceanBiome.java
src/main/java/cn/nukkit/level/generator/biome/PlainBiome.java
src/main/java/cn/nukkit/level/generator/biome/RiverBiome.java
src/main/java/cn/nukkit/level/generator/populator/PopulatorSugarcane.java
src/main/java/cn/nukkit/level/generator/populator/PopulatorTallSugarcane.java

This is untested.
I have added sugarcane and tall sugarcanes to be populated.
I am going to help implements mobs soon!

Add sugarcane populator and tall sugarcanes populator

---

src/main/java/cn/nukkit/Player.java

Falling - fail

---

src/main/java/cn/nukkit/block/BlockDoublePlant.java

I checked this problem,
actually Large Fern also can be replace,
Double Tallgrass
Large Fern(175:3)

Fixed #424

---

src/main/java/cn/nukkit/entity/item/EntityItem.java
src/main/java/cn/nukkit/event/entity/EntityPortalEnterEvent.java

EntityItem has a frequently tries to save the NBT value,
But often EntityItem->'item' value has null.

Fixed #676 #765 Problem

---

src/main/java/cn/nukkit/plugin/JavaPluginLoader.java

Not sure what others think about this but personally I would like to have my PC & PE plugin all in one big file, as I currently do with Spigot/BungeeCord.

Added fallback for plugin.yml to nukkit.yml

---

src/main/java/cn/nukkit/block/BlockLiquid.java

Liquids kept blowing up from TNT

Fix's TNT destroying liquids

---

src/main/java/cn/nukkit/block/BlockLever.java
src/main/java/cn/nukkit/level/sound/LeverSound.java

Added lever, but still some bugs.

Add Lever?

---

src/main/java/cn/nukkit/Player.java
src/main/java/cn/nukkit/level/ChunkHandler.java
src/main/java/cn/nukkit/level/Level.java
src/main/java/cn/nukkit/level/format/LevelProvider.java
src/main/java/cn/nukkit/level/format/anvil/Anvil.java
src/main/java/cn/nukkit/level/format/leveldb/LevelDB.java
src/main/java/cn/nukkit/level/format/mcregion/McRegion.java
src/main/java/cn/nukkit/level/generator/task/RequestChunkTask.java

Enhanced asynchronous processing
I just added requestChunk and some more things..
It might be help for multi-core server performance

Chunk performance improved

---

src/main/java/cn/nukkit/inventory/CraftingManager.java

Fix recipes

---

src/main/java/cn/nukkit/level/ChunkHandler.java
src/main/java/cn/nukkit/level/ChunksHandler.java
src/main/java/cn/nukkit/level/Level.java
src/main/java/cn/nukkit/level/RegionPool.java
src/main/java/cn/nukkit/level/format/anvil/Anvil.java
src/main/java/cn/nukkit/level/format/leveldb/LevelDB.java
src/main/java/cn/nukkit/level/format/mcregion/McRegion.java
src/main/java/cn/nukkit/level/generator/task/PopulationTask.java

populateChunk(...) also changed asynchronously.
@MagicDroidX

Chunk performance improved (2)

---

src/main/java/cn/nukkit/level/Level.java
src/main/java/cn/nukkit/level/format/LevelProvider.java
src/main/java/cn/nukkit/level/format/anvil/Anvil.java
src/main/java/cn/nukkit/level/format/leveldb/LevelDB.java
src/main/java/cn/nukkit/level/format/mcregion/McRegion.java

Changed the chunks save in an asynchronous.

Chunk performance improved (3)

---

src/main/java/cn/nukkit/Player.java

Fix for #828, I'm not sure if that's the best way to implement it, if this isn't the best way, at least add a "setInAirTicks" method. :)

Reset inAirTicks when changing flight mode

---

src/main/java/cn/nukkit/item/enchantment/Enchantment.java

Allows compact adding enchantment like this: ```Item.get(1,0,1).addEnchantment(Enchantment.get(1).setLevel(2))```

More compact setLevel

---

src/main/java/cn/nukkit/Player.java

Fix interact with door cancelling

---

src/main/java/cn/nukkit/utils/Utils.java

Small fix but big deal. Nice teamwork: one "close()" by @Pub4Game , another one bye fromgate :)

Close everything to prevent memory leaks. 

---

src/main/java/cn/nukkit/Player.java
src/main/java/cn/nukkit/network/RakNetInterface.java
src/main/java/cn/nukkit/network/SourceInterface.java
src/main/java/cn/nukkit/raknet/server/Session.java

Now you can get ping value for every player.

Add network latency measurement

---

src/main/java/cn/nukkit/item/ItemBucket.java

Fixed the bucket bugs: Error stack count; Display error in the state of the bucket.
Fixed the wrong bucket event calling!

Fixed a lot of bucket bugs

---

src/main/java/cn/nukkit/raknet/server/UDPServerSocket.java

It is the cause of raising memory usage and frequent garbage collection. Fixes #969 (**really** fixes), I believe.
Before:
After:
Why did I remove it completely? Because there is no difference. There's no sense in using nonblocking sockets like this.

Remove faulty "nio"

---

src/main/java/cn/nukkit/Player.java
src/main/java/cn/nukkit/command/Command.java
src/main/java/cn/nukkit/command/defaults/StatusCommand.java
src/main/java/cn/nukkit/network/rcon/RCON.java
src/main/java/cn/nukkit/timings/TimingsExport.java
src/main/java/cn/nukkit/utils/MainLogger.java
src/main/java/cn/nukkit/utils/TextFormat.java

I think there too much code in Nukkit that was directly translated from PM without using Java's alternatives. So I decided to make this a pull request that changes the TextFormat class. 
I hope you will understand that these changes are necessary :smiling_imp: 
+1 https://github.com/Nukkit/Nukkit/issues/466
**NOT TO ACCEPT THIS PULL REQUEST**

[ATTENTION] TextFormat - this will break your plugin!

---

src/main/java/cn/nukkit/network/rcon/RCON.java

RCON: Add Translations

---

src/main/java/cn/nukkit/raknet/server/UDPServerSocket.java

Before the server would never fully stop.
Looks like it was a simple fix. Maybe even a hack.

Fixing /stop #992

---

src/main/java/cn/nukkit/entity/EntityLiving.java

Now uses Integer[] instead of strange Map

Better getLineOfSight and getTargetBlock

---

src/main/java/cn/nukkit/inventory/CraftingManager.java

Changing the recipe for the golden apple to PC's version

Update Golden Apple Recipe to PC

---

src/main/java/cn/nukkit/block/BlockLiquid.java

Really fixed!!! No any negative effects I found, really closed #923.

Fix bugs with liquids

---

src/main/java/cn/nukkit/utils/TextFormat.java

Insignificant changes for TextFormat

---

src/main/java/cn/nukkit/level/generator/object/tree/ObjectSpruceTree.java

Fix spruce tree generation (Fixes #738)

---

src/main/java/cn/nukkit/scheduler/ServerScheduler.java

Fixed random order in task queue.

Task should run FIFO if run in same tick

---

src/main/java/cn/nukkit/scheduler/AsyncTask.java

Fixed unhandled exception in AsyncTask.collectTask

---

src/main/java/cn/nukkit/Server.java
src/main/java/cn/nukkit/network/protocol/AddEntityPacket.java
src/main/java/cn/nukkit/utils/Utils.java

Minor fixes

---

src/main/java/cn/nukkit/Player.java

 Check the player's health before spawning it, thanks @imjack for helping

---

src/main/java/cn/nukkit/Player.java
src/main/java/cn/nukkit/utils/MainLogger.java

Small fixes for #1069

---

src/main/java/cn/nukkit/block/BlockFlowable.java
src/main/java/cn/nukkit/block/BlockWaterLily.java

From https://github.com/pmmp/PocketMine-MP/commit/2b6d0587603a970940454bb261fad90ed1edc24f

Fixed kicked for flying when walking on/staying above lily pads

---

src/main/java/cn/nukkit/block/BlockDoor.java

Movement fix from
https://github.com/ClearSkyTeam/ClearSky/commit/513b9dd38c0d4d1895d1bf9e4ce5add698017316

Fix "invalid movement" when walking through doors

---

src/main/java/cn/nukkit/block/BlockDoublePlant.java

This fixes all the three issues in #1075
However I'm not sure if this is the perfect solution, but it works.
@Creeperface01 said he will try fixing himself, if he doesn't create a
pull request, then pull this change. (Or pull this change and revert it
when @Creeperface01 creates his fix)

Workaround for double flowers

---

src/main/java/cn/nukkit/Server.java
src/main/java/cn/nukkit/block/Block.java
src/main/java/cn/nukkit/block/BlockCauldron.java
src/main/java/cn/nukkit/blockentity/BlockEntity.java
src/main/java/cn/nukkit/blockentity/BlockEntityCauldron.java
src/main/java/cn/nukkit/entity/EntityHumanType.java
src/main/java/cn/nukkit/event/player/PlayerGlassBottleFillEvent.java
src/main/java/cn/nukkit/item/Item.java
src/main/java/cn/nukkit/item/ItemCauldron.java
src/main/java/cn/nukkit/item/ItemGlassBottle.java
src/main/java/cn/nukkit/level/sound/ExplodeSound.java
src/main/java/cn/nukkit/level/sound/SplashSound.java
src/main/java/cn/nukkit/network/protocol/LevelEventPacket.java

its able to merge now so i hope you can merge it before it wont be able to merge :D

Add Cauldron

---

src/main/java/cn/nukkit/entity/Entity.java
src/main/java/cn/nukkit/entity/EntityLiving.java
src/main/java/cn/nukkit/entity/ai/EntityMoving.java
src/main/java/cn/nukkit/entity/mob/EntityFlyingMonster.java
src/main/java/cn/nukkit/entity/mob/EntityWalkingMonster.java
src/main/java/cn/nukkit/entity/passive/EntityFlyingAnimal.java
src/main/java/cn/nukkit/entity/passive/EntityWalkingAnimal.java

Class structure. This is to prevent probable bugs might cause by plugins.

Small fixes

---

src/main/java/cn/nukkit/entity/Entity.java
src/main/java/cn/nukkit/entity/EntityLiving.java
src/main/java/cn/nukkit/entity/ai/EntityMoving.java
src/main/java/cn/nukkit/entity/mob/EntityFlyingMonster.java
src/main/java/cn/nukkit/entity/mob/EntityWalkingMonster.java
src/main/java/cn/nukkit/entity/passive/EntityFlyingAnimal.java
src/main/java/cn/nukkit/entity/passive/EntityWalkingAnimal.java

Revert "Small fixes"

---

src/main/java/cn/nukkit/level/generator/populator/PopulatorCaves.java

More caves!

---

src/main/java/cn/nukkit/block/BlockDoublePlant.java

Fixes #1110 and #1075 without breaking flower physics

Double Flower Shenanigans

---

src/main/java/cn/nukkit/Player.java

Fixed chunk loading on join

---

src/main/java/cn/nukkit/block/BlockLiquid.java
src/main/java/cn/nukkit/event/block/BlockFromToEvent.java

Implements BlockFromToEvent

---

src/main/java/cn/nukkit/Player.java
src/main/java/cn/nukkit/Server.java

fixes PlayerList Not Update #1156

---

src/main/java/cn/nukkit/utils/BinaryStream.java

Reverts Nukkit/Nukkit#1122
Because this breaks Synapse when logging into a server. I crash when the chunks are being loaded sort of.

Revert "Binary stream optimizations"

---

pom.xml
src/main/java/cn/nukkit/utils/MainLogger.java

Use MainLogger from https://github.com/Nukkit/Nukkit/pull/1102 as current logger isn't thread safe

Fixes #1201 Fixes #1192

---

src/main/java/cn/nukkit/Player.java
src/main/java/cn/nukkit/inventory/SimpleTransactionGroup.java
src/main/java/cn/nukkit/inventory/TransactionGroup.java

(mostly affected win 10)
Creative can execute any transaction
Creative can try to drop any item
Send current item on invalid transaction

Inventory fixes

---

src/main/java/cn/nukkit/block/Block.java
src/main/java/cn/nukkit/block/BlockCocoa.java
src/main/java/cn/nukkit/block/BlockLeaves2.java
src/main/java/cn/nukkit/item/Item.java
src/main/java/cn/nukkit/item/ItemDye.java
src/main/java/cn/nukkit/level/generator/biome/IcePlainsBiome.java

Add cocoa beans

---

src/main/java/cn/nukkit/Player.java

- Vertical movement was already checked above: if (diffY >= -yS || diffY
<= yS)
- Fixes #420 
Alternative solution to #1128

Validate horizontal and vertical movement separately

---

pom.xml
src/main/java/cn/nukkit/utils/MainLogger.java

Ansi fixes

---

src/main/java/cn/nukkit/plugin/JavaPluginLoader.java

Close jar when getting description

---

src/main/java/cn/nukkit/level/particle/Particle.java
src/main/java/cn/nukkit/network/protocol/AddEntityPacket.java
src/main/java/cn/nukkit/network/protocol/AddPlayerPacket.java

Fix Following Bug https://github.com/Nukkit/Nukkit/issues/1236

Fix Following Bug: issue#1236

---

src/main/java/cn/nukkit/network/protocol/ChunkRadiusUpdatedPacket.java
src/main/java/cn/nukkit/network/protocol/RequestChunkRadiusPacket.java

Fix chunks

---

src/main/java/cn/nukkit/network/protocol/LevelSoundEventPacket.java

Example (Tested OK):
```java
LevelSoundEventPacket pk = new LevelSoundEventPacket();
pk.x = (int) noteBlock.x;
pk.y = (int) noteBlock.y;
pk.z = (int) noteBlock.z;
pk.type = LevelSoundEventPacket.SOUND_NOTE;
pk.case1 = note.getInstrument();   //0->piano 1->drum, ....
pk.case2 = note.getKey() - 33;
player.dataPacket(pk);
```

Sound fix for 0.16

---

src/main/java/cn/nukkit/Player.java

Fix #1255 #1223

---

src/main/java/cn/nukkit/Player.java

Kick message need be the "String reasonString" not the "PlayerKickEvent.Reason reason".

Kick message need be the "String reasonString"

---

src/main/java/cn/nukkit/command/defaults/ParticleCommand.java
src/main/java/cn/nukkit/level/particle/BlockForceFieldParticle.java
src/main/java/cn/nukkit/level/particle/HugeExplodeSeedParticle.java
src/main/java/cn/nukkit/level/particle/Particle.java

From https://github.com/pmmp/PocketMine-MP/commit/7314aaf7f7bdae582f674c085c7ae879985bf847

Fix Particles for 0.16

---

src/main/java/cn/nukkit/Player.java

it will fix an error when use /xp command
(now i know how to create pull requests! :D)
https://github.com/Nukkit/Nukkit/issues/1280

fixed "calculateRequireExperience(int level)"

---

src/main/java/cn/nukkit/Server.java
src/main/java/cn/nukkit/plugin/JavaPluginLoader.java
src/main/java/cn/nukkit/plugin/service/NKServiceManager.java
src/main/java/cn/nukkit/plugin/service/RegisteredServiceProvider.java
src/main/java/cn/nukkit/plugin/service/ServiceManager.java
src/main/java/cn/nukkit/plugin/service/ServicePriority.java

It similar to bukkit's impl but more simple and convenient.

Add a service manager

---

src/main/java/cn/nukkit/Server.java
src/main/java/cn/nukkit/block/BlockBeacon.java
src/main/java/cn/nukkit/blockentity/BlockEntity.java
src/main/java/cn/nukkit/blockentity/BlockEntityBeacon.java

Please review; feedback welcome.

Make the Level flag work so that the beacons light up. No GUI yet.

---

src/main/java/cn/nukkit/block/BlockCocoa.java

Fix problem that can not be placed on other face

Fix cocoa block bug

---

src/main/java/cn/nukkit/math/Vector2.java
src/main/java/cn/nukkit/math/Vector2f.java
src/main/java/cn/nukkit/math/Vector3.java
src/main/java/cn/nukkit/math/Vector3f.java

if y = -1.1, getFloorY() must be return -2, but i had received -1.

Fix wrong getFloor at Vector3

---

src/main/java/cn/nukkit/block/BlockDoorIron.java
src/main/java/cn/nukkit/blockentity/BlockEntityFurnace.java
src/main/java/cn/nukkit/inventory/CraftingManager.java

Fixed stone brick recipe, fixed bucket burning, fixed iron door drop.

Fix various inconsistencies

---

src/main/java/cn/nukkit/level/format/anvil/Anvil.java

Send all chunk sections to player
Closes https://github.com/Nukkit/Nukkit/issues/1268
Maybe closes https://github.com/Nukkit/Nukkit/issues/1359

Fix teleport issue between worlds

---

src/main/java/cn/nukkit/level/Level.java

Fix getBlock #blameme

---

src/main/java/cn/nukkit/Player.java
src/main/java/cn/nukkit/level/format/anvil/Anvil.java

From https://github.com/pmmp/PocketMine-MP/commit/162b993e65f2e15b25d1997af3b0e77db2bc2de7
Closes #1396

Fix chunk sending

---

src/main/java/cn/nukkit/Player.java
src/main/java/cn/nukkit/entity/Entity.java
src/main/java/cn/nukkit/event/player/PlayerToggleGlideEvent.java
src/main/java/cn/nukkit/item/Item.java
src/main/java/cn/nukkit/item/ItemElytra.java

Support Gliding and add ItemElytra

---

src/main/java/cn/nukkit/Player.java
src/main/java/cn/nukkit/level/format/anvil/Anvil.java

From https://github.com/pmmp/PocketMine-MP/commit/0944064eb8dcdbda77a0b9811281b6255efa246a
Tested, it worked well with no lag.

Add a better hack for multi-world

---

src/main/java/cn/nukkit/network/RakNetInterface.java
src/main/java/cn/nukkit/utils/Utils.java

From https://github.com/pmmp/PocketMine-MP/commit/cb55cefa44bd609342c2e84477197ac525e4331c

Fix trailing slashes in MOTD breaks server list

---

README.md
src/main/java/cn/nukkit/utils/TextFormat.java

Small changes in the README and TextFormat.

Small changes

---

src/main/java/cn/nukkit/Player.java

I was using that when I was debugging the ACK response, but I forgot to remove it when I submitted the pull request.

Remove "while (true) { ... }" from sendCommandData()

---

src/main/java/cn/nukkit/block/BlockLeaves.java

2nd Fixed TreeDecay #1341

---

src/main/java/cn/nukkit/block/BlockItemFrame.java

Keep the item's NBT tags on the item frame, fixes #1426

---

src/main/java/cn/nukkit/raknet/server/Session.java

From https://github.com/pmmp/RakLib/commit/f4bfcb8e6b7cf93f3961dd8fc9c5ba44ce068763

Fix disconnect message sometimes does not show.

---

src/main/java/cn/nukkit/Player.java

From PM-MP: https://github.com/pmmp/PocketMine-MP/commit/f881cea8e0ea07e147dfb6806276a1450f250428

Remove some unused properties from Player

---

pom.xml
src/main/java/cn/nukkit/command/CommandReader.java
src/main/java/cn/nukkit/utils/completers/CommandsCompleter.java
src/main/java/cn/nukkit/utils/completers/PlayersCompleter.java

Update JLine to 2.14.2, add player/command TAB completer to console, fix Nukkit's console when using Nukkit + JRebel

---

src/main/java/cn/nukkit/network/protocol/ProtocolInfo.java
src/main/java/cn/nukkit/network/protocol/TransferPacket.java

Pocket Protocol Update (101/MCPE 1.0.3.0)

---

src/main/java/cn/nukkit/block/BlockVine.java

Break vines which are not attached to something solid and are not held up by another vine.

Remove floating vines

---

src/main/java/cn/nukkit/entity/Entity.java

Finally!!! :D i could not figure it out due to ignored exception...

Fix entity initializing

---

src/main/java/cn/nukkit/Server.java

Destroying the server state is too simple now

Let Server instance safe

---

src/main/java/cn/nukkit/inventory/BaseInventory.java

Armor isn't removed, when player wears it. (`contains()` returns `true`)

Fix armor not removing

---

src/main/java/cn/nukkit/Player.java
src/main/java/cn/nukkit/Server.java

Added an option to turn off achievements.

Turn off achievements

---

src/main/java/cn/nukkit/Player.java
src/main/java/cn/nukkit/entity/Entity.java
src/main/java/cn/nukkit/inventory/PlayerInventory.java
src/main/java/cn/nukkit/level/Level.java
src/main/java/cn/nukkit/network/Network.java
src/main/java/cn/nukkit/network/protocol/LevelSoundEventPacket.java
src/main/java/cn/nukkit/network/protocol/ProtocolInfo.java
src/main/java/cn/nukkit/network/protocol/UpdateTradePacket.java
src/main/java/cn/nukkit/potion/Effect.java
src/main/java/cn/nukkit/utils/BinaryStream.java

Currently has an issue with every entity assuming it's been traded with [image](http://i.imgur.com/5bQbYzp.png) used https://github.com/sel-project/sel-utils to get the updates

1.04 Update

---

src/main/java/cn/nukkit/network/protocol/UpdateTradePacket.java

from https://github.com/pmmp/PocketMine-MP/commit/f87b7457713c9bde26337221c389751a9ae45f52

Update some UpdateTradePacket fields

---

src/main/java/cn/nukkit/block/BlockSugarcane.java

Sugarcane wasn't growing.
Bonemeal didn't make sugarcane grow at all; it should grow to a height of 3.

Sugarcane Growing

---

src/main/java/cn/nukkit/Player.java
src/main/java/cn/nukkit/block/BlockItemFrame.java
src/main/java/cn/nukkit/event/player/PlayerMapInfoRequestEvent.java
src/main/java/cn/nukkit/inventory/ShapedRecipe.java
src/main/java/cn/nukkit/item/Item.java
src/main/java/cn/nukkit/item/ItemMap.java
src/main/java/cn/nukkit/network/protocol/ClientboundMapItemDataPacket.java
src/main/java/cn/nukkit/utils/Utils.java

I also added some map saving, I know its bad, but idk how to save in, because map data are long array and we need byte array. But it works. The only problem is when player take the map item from item frame and pickup it, because it throws EOF exception, idk if maybe player sends bad comppound tag

Added basic map API

---

src/main/java/cn/nukkit/inventory/InventoryType.java
src/main/java/cn/nukkit/item/Item.java
src/main/java/cn/nukkit/item/ItemBlazeRod.java
src/main/java/cn/nukkit/item/ItemBoat.java
src/main/java/cn/nukkit/item/ItemCarrotOnAStick.java
src/main/java/cn/nukkit/item/ItemFishingRod.java
src/main/java/cn/nukkit/item/ItemHorseArmorDiamond.java
src/main/java/cn/nukkit/item/ItemHorseArmorGold.java
src/main/java/cn/nukkit/item/ItemHorseArmorIron.java
src/main/java/cn/nukkit/item/ItemHorseArmorLeather.java
src/main/java/cn/nukkit/item/ItemMinecart.java
src/main/java/cn/nukkit/item/ItemMinecartChest.java
src/main/java/cn/nukkit/item/ItemMinecartHopper.java
src/main/java/cn/nukkit/item/ItemMinecartTNT.java
src/main/java/cn/nukkit/item/ItemSaddle.java

Fix reduant slots in player inventory (#1541)
Fix getMaxStackSize() for some items (#1542)
Add ItemCarrotOnAStick.class
Add ItemBlazeRod.class (#1520)

Fix #1520, #1541, #1542

---

README.md

I basically just fixed some markdown issues.

Fixed Header level 4 markdown in README.md

---

src/main/java/cn/nukkit/math/Angle.java
src/test/java/cn/nukkit/test/AngleTest.java

This tool class helps our plugin developers, as they had to use `Math.PI` and many conversaions in doing the math on angles before. 
Instructions:
```java
// All instances of this class is immutable
public final class Angle implements Comparable<Angle> {
// Creates an Angle instance from a float degree value
public static Angle fromDegree(float floatDegree) ...
// Creates an Angle instance from a double degree value
public static Angle fromDegree(double doubleDegree) ...
// Creates an Angle instance from a float radian value
public static Angle fromRadian(float floatRadian) ...
// Creates an Angle instance from a double radian value
public static Angle fromRadian(double doubleRadian) ...
// Calculates a/c into an Angle instance valued by asin(v), in which v=a/c
public static Angle …
```

Class Angle. Now you are no longer confused by DEGREE or RADIAN angle values.

---

src/main/java/cn/nukkit/Achievement.java
src/main/java/cn/nukkit/Player.java
src/main/java/cn/nukkit/entity/mob/EntityCreeper.java
src/main/java/cn/nukkit/entity/passive/EntitySheep.java

Fixed Sheep wool color on drop. (Fix Issue #1573)
Added gunpowder drop to Creeper
Fix Issue #1698 
Fix Issue #1497

Fixed a few issues reported, and added gunpowder to Creepers 

---

src/main/java/cn/nukkit/Server.java
src/main/java/cn/nukkit/entity/mob/EntityZombie.java
src/main/java/cn/nukkit/item/Item.java

+EntityZombie, +Zombie Spawn Egg, +Zombie Drops

+EntityZombie, +Zombie Spawn Egg

---

src/main/java/cn/nukkit/inventory/PlayerInventory.java
src/main/java/cn/nukkit/nbt/NBTIO.java

1. Fix support on string block/item id (support for world formats created by minecraft PC 1.8+)
2. Fix https://github.com/Nukkit/Nukkit/issues/1553
Thank you @boybook

Fixes by @boybook

---

src/main/java/cn/nukkit/item/Item.java

https://github.com/Nukkit/Nukkit/pull/1697
Sorry @Tee7even @Creeperface01

Lore API, can be used to show custom message in win10 edition

---

src/main/java/cn/nukkit/block/BlockMushroomRed.java
src/main/java/cn/nukkit/block/BlockPressurePlateBase.java

https://github.com/Nukkit/Nukkit/pull/1722

Remove debug message

---

src/main/java/cn/nukkit/network/protocol/ProtocolInfo.java

No protocol and functional changes

Update to 1.1.2

---

src/main/java/cn/nukkit/inventory/CraftingManager.java
src/main/java/cn/nukkit/utils/BinaryStream.java

Fixed https://github.com/Nukkit/Nukkit/issues/1770

Fixed furnaces and more stoneware crafting bug

---

src/main/java/cn/nukkit/network/protocol/ProtocolInfo.java

Update to 1.1.3

---

src/main/java/cn/nukkit/event/potion/PotionApplyEvent.java
src/main/java/cn/nukkit/potion/Potion.java

Add API to get and change the apply effect when a potion applied on an entity.

Add the support to change Apply Effect in PotionApplyEvent

---

src/main/java/cn/nukkit/Player.java

logged out due to Transferred to 43.xxx.xx.xx/43.xx.xx.xx:12345:12345
-.-

Fix Bug HostName Transfer

---

src/main/java/cn/nukkit/command/defaults/PardonIpCommand.java
src/main/java/cn/nukkit/network/AdvancedSourceInterface.java
src/main/java/cn/nukkit/network/Network.java
src/main/java/cn/nukkit/network/RakNetInterface.java
src/main/java/cn/nukkit/raknet/RakNet.java
src/main/java/cn/nukkit/raknet/server/ServerHandler.java
src/main/java/cn/nukkit/raknet/server/SessionManager.java

**COMPLETE**.
Need test. Anyone can? 👍

Added capability to unblock addresses without a restart

---

src/main/java/cn/nukkit/Nukkit.java
src/main/java/cn/nukkit/utils/LogLevel.java
src/main/java/cn/nukkit/utils/MainLogger.java

Using the command line parameter `--verbosity` or `-v`
The log level is case-insensitive.
For example, 
`java -jar Nukkit.jar -v none`
`java -jar Nukkit.jar --verbosity emergency`

Allows for the log level to be changed

---

src/main/java/cn/nukkit/utils/Zlib.java

Fix https://github.com/Nukkit/Nukkit/issues/1837

Revert "Fix for issue #1817 -- main thread stuck (rollback Zlib)"
