Nukkit/Nukkit

src/main/java/cn/nukkit/network/protocol/InteractPacket.java
The field `eid` ignored on PM(Maybe a bug?). Please review this code.
=> Implements InteractPacket

src/main/java/cn/nukkit/level/generator/task/PopulationTask.java
这是治标不治本。你去看看Level.registerGenerator是怎么搞的吧，几个线程不停的覆盖表里面的levelId这个key，我看了表示很囧。
既然表是以levelId作为唯一索引的，给每个Level注册N个Generator意义何在。
请谨慎使用多线程。请谨慎对待资源竞争。
每个Level的交给一个Gnerator处理，每个Generator交给一个线程处理。
=> Fix NullPointerException in chunk generator

src/main/java/cn/nukkit/plugin/PluginBase.java
If you trying to save resource file using method plugin.saveResource ("lang/russian.lng", false); you can save it only to "<PluginName>/lang/russian.lng". 
But I think we need ability to save resource to file located anywhere (without keeping file path and name).
For example:
File out = new File ("current-language.lng");
plugin.saveResource ("lang/russian.yml", false,out);
=> Add ability to save resource to defined file

src/main/java/cn/nukkit/utils/Config.java
Currently Config.remove() doesn't work with nested configuration nodes. This does.
=> Add removeNested()

src/main/java/cn/nukkit/command/defaults/TeleportCommand.java
supports:
/tp \<player2>
/tp \<player1> \<player2>
/tp \<x> \<y> \<z>
/tp \<player1> \<x> \<y> \<z>
/tp \<x> \<y> \<z> \<x-rot> \<y-rot>
/tp \<player1> \<x> \<y> \<z> \<x-rot> \<y-rot>
=> totally rewrite /tp

src/main/java/cn/nukkit/entity/Entity.java
Prior to this, isSneaking or isSprinting would **always** be true. This fixes that issue, I could not find any other issues arising as a result of this fix.
=> Fixes setDataFlag, used to always create new objects.

src/main/java/cn/nukkit/level/Level.java
This change stops the constant spam of NPEs if a level is unloaded by a plugin. It also stops the NPE on shutdown.
Here's the error it used to spam:
```
2016-1-29 03:54:24 [ALERT] java.lang.NullPointerException
at cn.nukkit.level.Level.getName(Level.java:2353)
at cn.nukkit.Server.checkTickUpdates(Server.java:908)
at cn.nukkit.Server.tick(Server.java:942)
at cn.nukkit.Server.tickProcessor(Unknown Source)
at cn.nukkit.Server.start(Unknown Source)
at cn.nukkit.Server.<init>(Unknown Source)
at cn.nukkit.Nukkit.main(Nukkit.java:52)
```
=> Remove level from level map upon closing.

.gitignore, pom.xml
This is a very small change to remove some of the warnings that you get when building the project and make it easier for new developers to pick the project up (like me).
It is very simple stuff, except the enforcer plugin which may be controversial.  It ensures that you don't have 2 different versions of the same jar in the dependency tree - which can cause some bad problems with the shaded jar.  Without enforcer you may not realise there is a problem until things start going wrong in random ways :-(.
=> Added default file encoding and enforcer plugin to pom.

src/main/java/cn/nukkit/nbt/stream/NBTInputStream.java, src/main/java/cn/nukkit/nbt/stream/NBTOutputStream.java
No longer subclasses FilterInputStream/FilterOutputStream, implements AutoCloseable.
This should improve performance and simplify usage since not all of
the InputStream/OutputStream API is needed.
=> Simplify NBTInputStream and NBTOutputStream

src/main/java/cn/nukkit/Player.java, src/main/java/cn/nukkit/entity/Entity.java
1. Player spawn/respawn/bed will not fire PlayerTeleportEvent
2. Player teleporting will fire only PlayerTeleportEvent, but will not fire EntityTeleportEvent
3. When teleport cause is null events will not fired.
=> Fixing teleports

src/main/java/cn/nukkit/event/player/PlayerDeathEvent.java
There's no reason to not let PlayerDeathEvent be cancellable. Look at #682 for reference.
@Pub4Game Happy?
=> PlayerDeathEvent should be cancellable.

src/main/java/cn/nukkit/block/BlockBricksStone.java, src/main/java/cn/nukkit/block/BlockEndPortalFrame.java, src/main/java/cn/nukkit/entity/Entity.java
Tested in singleplayer, dropped items do not pop out of transparent blocks. This fixes #715.
=> Fix bouncing items

src/main/java/cn/nukkit/command/SimpleCommandMap.java
Also commented the method since I had trouble understanding exactly what was meant by the statement.
I would like the ability to override the /ban /msg and other vanilla commands with my plugins. I believe this would be a common use case. Any plugin that does override /ban intentionally does so, and so vanilla commands should respect that.
=> Any command can override vanilla commands.

src/main/java/cn/nukkit/block/BlockLiquid.java
BlockLiquid.java at 331 and 203, its parameter updates is set as true, which results in updating block. Thus, scheduling update is duplicating code. Also, water flows normally even if the code is removed.
=> Removal of not needed code

src/main/java/cn/nukkit/network/rcon/RCONServer.java
So may some `BufferUnderflowException`s not bother you.
=> RCON: Ignore corrupted packets

src/main/java/cn/nukkit/network/Network.java
This method is required to perform additional analyses and filter unnecessary packets. Now it fix double fire of PlayerInteractEvent
=> Add additional method to process batch packets. 

src/main/java/cn/nukkit/Player.java, src/main/java/cn/nukkit/command/SimpleCommandMap.java
And changes in command processing related to them. Escaping of spaces, escaping of quotes, escaping of escaping... Do we need to go deeper?
A small tutorial:
Space can be escaped like this - `this\ is\ the\ same\ argument`
and like this - `"this is one argument too"`,
you can escape the quotes like this - `\"`,
backslash itself can be escaped too - `\\`.
=> Names with spaces.

src/main/java/cn/nukkit/level/Level.java, src/main/java/cn/nukkit/level/format/LevelProvider.java, src/main/java/cn/nukkit/level/format/generic/BaseLevelProvider.java, src/main/java/cn/nukkit/level/format/leveldb/LevelDB.java
Update level name during level loading (to prevent situation when two (or more) level could have same names)
=> Update level name during level loading 

src/main/java/cn/nukkit/level/Level.java
courtesy of @dktapps
explanation:
**Before patch**:
Chunk is unloaded and saved. All entities on the chunk are saved. Level::removeEntity is called on all entities in that chunk to remove them.
Level::removeEntity kills non-player entities. Result is items and XP being spawned in an unloaded chunk.
Movement updates to these entitities (falling checks etc.) trigger requests to the blocks around the entities. Because the entities are in unloaded chunks, these requests cause the chunks to be reloaded. When the chunk is reloaded, the saved entities are spawned again.
Process repeats, leaking more and more entities until memory limit is exhausted.
**After patch**:
Chunk is unloaded and saved. All entities on the chunk are saved. Level::removeEntity is called on all entities in that chunk to …
=> fix memory leak

src/main/java/cn/nukkit/block/BlockCarpet.java, src/main/java/cn/nukkit/block/BlockClayHardened.java, src/main/java/cn/nukkit/block/BlockClayStained.java, src/main/java/cn/nukkit/block/BlockFarmland.java, src/main/java/cn/nukkit/block/BlockWool.java, src/main/java/cn/nukkit/inventory/EnchantInventory.java, src/main/java/cn/nukkit/item/ItemColorArmor.java, src/main/java/cn/nukkit/item/ItemDye.java, src/main/java/cn/nukkit/item/randomitem/Fishing.java, src/main/java/cn/nukkit/utils/BlockColor.java, src/main/java/cn/nukkit/utils/DyeColor.java
Added DyeColor enum. This enum allows to get color data of dye and wool and clay blocks. And could be used to construct dyes, wool, carpet, stained clay.
BTW, enchantment confusion (lapis vs yellow dye) fixed too.
No plugins were harmed: old ItemDye fields and methods are marked as deprecated but still could used by plugins.
=> DyeColor enum

src/main/java/cn/nukkit/command/CommandMap.java, src/main/java/cn/nukkit/command/SimpleCommandMap.java, src/main/java/cn/nukkit/command/simple/Arguments.java, src/main/java/cn/nukkit/command/simple/Command.java, src/main/java/cn/nukkit/command/simple/CommandPermission.java, src/main/java/cn/nukkit/command/simple/ForbidConsole.java, src/main/java/cn/nukkit/command/simple/SimpleCommand.java
Allows simple command handling, when there's much commands (compared to both creating a separate class for every command and switching them in "onCommand" method). =)
```
public class SomeCommandsClass { //Can be any class, but it makes sense to create a class just for commands :)
@Command( //This annotation is necessary to register a command
name = "test", //this annotation field is necessary
description = "Just a SimpleCommand test",
usageMessage = "/test <> []",
aliases = {"t", "tst"}
)
@Arguments(min = 1, max = 2) //Optional, you can specify either maximum or minimum number of arguments
@CommandPermission("simplecommand.test") //Optional
@ForbidConsole //Optional
public boolean test(CommandSender sender, String label, String[] args) {
sender.sendMessage("Hello, sender! Your args:"); …
```
=> SimpleCommand API

src/main/java/cn/nukkit/Player.java, src/main/java/cn/nukkit/Server.java, src/main/java/cn/nukkit/entity/Entity.java, src/main/java/cn/nukkit/level/Explosion.java, src/main/java/cn/nukkit/level/Level.java, src/main/java/cn/nukkit/level/Location.java, src/main/java/cn/nukkit/level/SimpleChunkManager.java, src/main/java/cn/nukkit/level/format/LevelProvider.java, src/main/java/cn/nukkit/level/format/anvil/Anvil.java, src/main/java/cn/nukkit/level/format/leveldb/LevelDB.java, src/main/java/cn/nukkit/level/format/mcregion/McRegion.java, src/main/java/cn/nukkit/math/BlockVector3.java, src/main/java/cn/nukkit/raknet/server/SessionManager.java, src/main/java/cn/nukkit/utils/MainLogger.java
Fixes Nukkit not handling any packets
Use Long/BlockVector3 instead of strings for maps
Reduce cache size significantly by not storing redundant data
Reduce login time significantly by reducing min chunk radius
Reduce chunk load by avoiding processing extra data
Reduce memory usage by storing cache in weak map
Reduce memory usage by unloading chunks more often
Reduce memory usage by using soft reference for some block updates
- If gc'd it will send a chunk update instead (less memory usage)
Optimize collision checks
Optimize various things by reusing objects and avoiding unnecesary
creation
Add debug level 0 = does not log to file
=> Some fixes / optimizations

src/main/java/cn/nukkit/level/Level.java
* Remove unnecessary SetTimePacket spam
This is handled automatically client-side, as long as it is calculated
correctly server side there is no issue (unless the server hits a spot
of bad lag)
* Better client/server time sync when lagging
From
https://github.com/pmmp/PocketMine-MP/commit/e9f2bf0085e89955ec6eb7ff9b07b004e8153e2c
=> Better time ticking and sync

src/main/java/cn/nukkit/entity/item/EntityItem.java
Fixes #1072
Bug stacktrace:
```
2016-10-4 12:12:59 [INFO] Descarregando mundo "WarpVIP"
2016-10-4 12:12:59 [INFO] Descarregando mundo "FightArena"
2016-10-4 12:12:59 [INFO] Descarregando mundo "CoisasInuteis"
2016-10-4 12:12:59 [INFO] Descarregando mundo "world"
2016-10-4 12:12:59 [ALERT] java.lang.RuntimeException: java.lang.RuntimeException: java.lang.NullPointerException
at cn.nukkit.level.Level.saveChunks(Level.java:1122)
at cn.nukkit.level.Level.save(Level.java:1105)
at cn.nukkit.level.Level.save(Level.java:1089)
at cn.nukkit.level.Level.close(Level.java:399)
at cn.nukkit.level.Level.unload(Level.java:521)
at cn.nukkit.Server.unloadLevel(Server.java:1541)
at cn.nukkit.Server.forceShutdown(Server.java:723)
at cn.nukkit.Server.start(Server.java:770)
at …
```
=> Fix null items causing chunk corruption or failure on save.

src/main/java/cn/nukkit/entity/Entity.java
From
https://github.com/ClearSkyTeam/ClearSky/commit/b80b2f9c36a185106a6de1e255f396d7a0d71d0f
Okay, this one I don't know how to reproduce, but it seems related to LevelDB map importing.
=> Fix client crash (converted worlds)

src/main/java/cn/nukkit/plugin/MethodEventExecutor.java
Finally we don't need to use "EntityDamageEvent" and then casting to
"EntityDamageByEntityEvent" just to get the damager!
Fixes #489
=> Fix "argument type mismatch" when using EntityDamageByEntityEvent

src/main/java/cn/nukkit/Player.java
From Genisys
https://github.com/iTXTech/Genisys/commit/dea6ecc73059bd9dd2ee4e59e5bfa16933250eb4
(Also, I always test my modifications (except those that I can't reproduce) before creating a pull request)
This has a issue because the stop/start sneak/sprint changes the player data flag to "No Action" so the server thinks we aren't pulling a bow anymore.
How to replicate:
1. Get a bow
2. Pull the bow but don't release
3. Sprint or sneak
4. Release the bow
The bow won't release a arrow, this fix changes the break to break the switch statement instead of breaking the current case.
=> Fix bow cannot be shot after sneaking/sprinting

src/main/java/cn/nukkit/plugin/MethodEventExecutor.java
This isn't a fancy fix, but I also have no idea why it thinks it should invoke EntityDamageEvent on a EntityDamageByEntityEvent. Probably later I will take a better look, but for now, this should work.
=> "Fix" ClassCastException when using EntityDamageByEntityEvent

src/main/java/cn/nukkit/raknet/server/SessionManager.java
Nukkit does not properly process empty packets. Since only a few packets at a time are processed, sending a sufficiently large number of them can freeze the RakLib thread and cause a denial of service.
See also pmmp/RakLib@bab1c10f1556009574ed7adc4deeaede284f1b2d
=> Fixes a DoS with empty packets

src/main/java/cn/nukkit/utils/BinaryStream.java
- Add a new buffer instead of resizing every write
- Join the buffers in parallel when requested
- Use buffer for common read sizes (short, int, long)
=> minor binary stream optimization

src/main/java/cn/nukkit/entity/Entity.java
> Farmland can now only be trampled if the player jumps onto it; walking no longer affects it. Animals, villagers, and other mobs can similarly trample farmland by jumping on it, but not by walking.
However the trample crop checks if the fallDistance is bigger than 1, but a player jump always return ~0.753
This changes the check so crop trampling behavior works as expected, instead of triggering only when you jump higher than 1 block. (Unless if I'm wrong and the default MCPE behavior is like that)
=> Change fallDistance to 0.75 instead of 1, fixes wrong crop trampling behavior.

src/main/java/cn/nukkit/Server.java
From
https://github.com/iTXTech/Genisys/commit/9bf5b94a1ff839c639a79c840532b370fd9649e9
TODO: Don't forget to add the default value to Nukkit config file!
Also, where it should be on the config file? I kept the original Genisys
value (player.save-player-data) but maybe we should change it for
Nukkit.
=> Added option to disable saving player.dat

src/main/java/cn/nukkit/utils/Binary.java
Not sure why batched packets were arbitrarily limited to 1024. It crashes the server with this sometimes:
> java.lang.ArrayIndexOutOfBoundsException: 1024
at cn.nukkit.utils.Binary.splitBytes(Binary.java:405)
at cn.nukkit.raknet.server.Session.addEncapsulatedToQueue(Session.java:267)
at cn.nukkit.raknet.server.SessionManager.receiveStream(SessionManager.java:332)
at cn.nukkit.raknet.server.SessionManager.tickProcessor(SessionManager.java:91)
at cn.nukkit.raknet.server.SessionManager.run(SessionManager.java:70)
at cn.nukkit.raknet.server.SessionManager.<init>(SessionManager.java:58)
at cn.nukkit.raknet.server.RakNetServer.run(RakNetServer.java:101)
For context, that's about 18 chunks
=> Fix packet sending

src/main/java/cn/nukkit/plugin/PluginManager.java
Fix #1181 .
Why exist this? E.g. plugin: MinecraftMarket . This works with Pokkit. Why is restricted plugin?
=> Remove resticts name. Wtf, why exist this?! 

src/main/java/cn/nukkit/Player.java, src/main/java/cn/nukkit/Server.java, src/main/java/cn/nukkit/command/defaults/BanCommand.java, src/main/java/cn/nukkit/command/defaults/BanIpCommand.java, src/main/java/cn/nukkit/command/defaults/KickCommand.java, src/main/java/cn/nukkit/event/player/PlayerKickEvent.java
Keeps old methods for compatiblity, but all existing code now uses the
PlayerKickEvent.Reason so it can be properly identified in an event.
=> Change kick API

src/main/java/cn/nukkit/block/Block.java
Previously the stone slab wouldn't register, leaving the block as null. When the level attempts to get that block (e.g. interacting with a stone slab) it would throw the error, and potentially crash the server.
=> Fix block slab registration, and regsiter unknown on failure

src/main/java/cn/nukkit/block/BlockStemMelon.java, src/main/java/cn/nukkit/block/BlockStemPumpkin.java
if you are placing a melon seed or pumpkin seed, it just changed to item entity. because BlockFarmland is extends BlockTransparent, so "useBreakOn(this)" method is executed.
this pr is fix the problem.
=> Fix BlockStemMelon, BlockStemPumpkin

src/main/java/cn/nukkit/block/BlockPumpkin.java, src/main/java/cn/nukkit/math/BlockVector3.java
Asking for a block at y-coordinate 255 currently returns whatever is at y-coordinate 0 (usually Bedrock) rather than recognising that 255 is an invalid y-coordinate and returning 0 (Air)
=> Add y-coordinate check to Vector3 .equals

src/main/java/cn/nukkit/Player.java, src/main/java/cn/nukkit/network/RakNetInterface.java
For some reason, while Nukkit processes the ACK notification, it doesn't do anything with it, so yes, any packet that were using "notifyACK" couldn't do anything with the notification, after all it wouldn't never receive it.
This commit changes that, it implements a very very very basic notifyACK method, changing the player's "needsACK" map (which wasn't used for NOTHING before this commit except adding packets that used the "needsACK" boolean (but it would just stay there with a "false" value so...)) to true if the server receives a notification from the client showing that yes, the client received the packet successfully.
Why that matters? This allows us to know IF the packet reached the client, allowing us to do a workaround for the #1378 issue.
So now we send a packet saying "hey …
=> Implement "notifyACK" method, change AvailableCommandsPacket to use "needsACK", fixes #1378

src/main/java/cn/nukkit/network/protocol/ItemFrameDropItemPacket.java
Yeah, you couldn't take out items from Item Frames because someone inverted the packet's coordinates...
Pull https://github.com/Nukkit/Nukkit/pull/1421 first, then pull this.
=> Blame @Pub4Game again, fixes Item Frames

src/main/java/cn/nukkit/Server.java, src/main/java/cn/nukkit/command/CommandReader.java
Also adds the ```Server#isPrimaryThread()``` to check if the current thread is the primary thread or not.
If a plugin tries to run a command in a async task, it warns the that a plugin is running a command in a async task. (Which is not good, see #1248)
=> Synchronize console commands, warn when a plugin tries to run a command in a async task, fixes #1248

src/main/java/cn/nukkit/Player.java
Doesn't fix 100% the dupe issue, but it's better than now.
Before:
After:
(The only issue is that only one message dupe... well, at least it's better than what it is now)
From PM-MP: https://github.com/pmmp/PocketMine-MP/commit/52748fcf64830453967fab4b43d6e823aeb37ecf
=> TODO: REVERT - Added a workaround for client text duplication

src/main/java/cn/nukkit/entity/EntityHumanType.java, src/main/java/cn/nukkit/inventory/PlayerInventory.java
Before this commit, EntityArmorChangeEvent was triggered every time the player received any kind of damage, and this is not the expected behavior since it is "EntityArmorChangeEvent", not "EntityArmorDamagedEvent".
So, to fix this, a new setItem/setArmorItem method needed to be created, allowing to bypass the armor change event check, fixing the issue.
**Taking damage:** No event thrown (expected behavior)
**Changing armors:** Event thrown (expected behavior)
Fixes https://github.com/Nukkit/Nukkit/issues/1434
=> Fix EntityArmorChangeEvent check, fixes #1434

src/main/java/cn/nukkit/item/enchantment/Enchantment.java, src/main/java/cn/nukkit/item/enchantment/EnchantmentWaterWorker.java
Yay for backwards compatibility.
**TODO:** Remove the old value (when the API is bumped to something else that isn't 1.0.0... come on, it's 2017, the API bump should happen one day)
=> Fix typo on Enchantment#UD_WATER_WORKER, deprecate old value

pom.xml
This started happening after https://github.com/Nukkit/Nukkit/commit/23b035e7f0659434b44286c0554947ef3f9f67f8, updating Jansi to 1.14 fixes the issue
=> Update Jansi to 1.14

src/main/java/cn/nukkit/Server.java
Okay, so now I could reproduce this issue again.
Disabling titleTick() fixes this, I will take a look on how to fix the titleTick() later, but for now, it is better disabling it. (if kept enabled, it will flood the console like in that screenshot)
=> Disable titleTick()

src/main/java/cn/nukkit/block/BlockSugarcane.java
Currently sugar cane blocks can be placed on water blocks, either at the surface or deep down.  This fix ensures only air blocks are replaced.
=> Only allow sugarcane to replace a block of air

src/main/java/cn/nukkit/Player.java, src/main/java/cn/nukkit/network/protocol/BossEventPacket.java
Adds a simple BossBar API.
You can create BossBar with ```Player#createBossBar("Hello World!", 100);```, this will return a bossBarId, store it for further use.
You can also update BossBar with ```Player#updateBossBar("New Text", 50, bossBarId);```, this will change the BossBar to show "New Text" and it will be half full.
And you can delete it with ```Player#deleteBossBar(bossBarId);```.
**TODO:** Nukkit is missing the Attributes value in AddEntityPacket, however sending the Attributes in the AddEntityPacket causes issues, client bug? (So, while this isn't fixed, the code uses UpdateAttributesPacket)
=> BossBar API

src/main/java/cn/nukkit/scheduler/ServerScheduler.java
Fixes #1458 
The tasks were never cancelled on reload because the plugin instance was always "null", so the code to cancel on reload were never executed.
Also fixes Tasks "onCancel" methods.
This pull request is required for https://github.com/Nukkit/Nukkit/pull/1457
=> Tasks should be cancelled on reload, deprecate old methods

src/main/java/cn/nukkit/scheduler/NukkitRunnable.java
Using Nukkit Scheduler is a mess, so I created NukkitRunnable.
It works just like BukkitRunnable... except it is for Nukkit 😉 
Example:
```
new NukkitRunnable() {
public void run() {
for (Player p : Server.getInstance().getOnlinePlayers().values()) {
if (bossBars.containsKey(p)) {
long bossBar = bossBars.get(p);
p.updateBossBar("Hello World! §a§l" + TasselUtils.getRandom().nextInt(0, 800), 100, bossBar);
} else {
long bossBar = p.createBossBar("Temporary", 100);
bossBars.put(p, bossBar);
}
}
}
}.runTaskTimer(this, 20, 20);
```
**Why I done this instead of using Nukkit Scheduler?**
Nukkit Scheduler doesn't let you cancel the task inside of the task, making you need to create a lot of unnecessary variables, bloating a lot your code.
Also, it's nice, and it works without any issues.
=> Add NukkitRunnable

src/main/java/cn/nukkit/Player.java, src/main/java/cn/nukkit/network/protocol/LoginPacket.java, src/main/java/cn/nukkit/network/protocol/ProtocolInfo.java, src/main/java/cn/nukkit/network/protocol/TransferPacket.java
* Autogenerated data for 1.0.3.0
From PM-MP: https://github.com/pmmp/PocketMine-MP/commit/bf6e8db941d4efae9859b2f773f275c533e34cd1
* Add TransferPacket (Doesn't work yet)
From ClearSky https://github.com/ClearSkyTeam/PocketMine-MP/commit/b2f2cd31bc4df1ded9101b2fa5bb01073e9b35f6
Doesn't work yet, the client disconnects from the server, shows "Connecting..." and then shows "Can't reach server"
* Short -> Little endian short, fixes TransferPacket
Thanks @Kripth :wink:
* Added default port 19132
From PM-MP: https://github.com/pmmp/PocketMine-MP/commit/770155500595e7537d74abeac08ed9ced629296c
* Should be 19132, not 1932
Thanks @Guillaume351 :wink:
=> Pocket Protocol Update (101/MCPE 1.0.3.0) (#1454)

src/main/java/cn/nukkit/item/ItemBucket.java
When STILL_WATER is removed using a bucket we now look for adjacent STILL_WATER and change it to WATER.  This WATER is now able to flow into the space where the STILL_WATER was removed.
The change avoids problems like this:
It looks like the same fix is required for lava, but I haven't checked.  I'll take a look another time.
=> Fixing water holes

src/main/java/cn/nukkit/network/protocol/ItemFrameDropItemPacket.java
The packet received doesn't seem to send the slot which results in an error. This fixes the error.
=> Item Frame error

src/main/java/cn/nukkit/command/data/CommandParameter.java, src/main/java/cn/nukkit/command/defaults/DefaultGamemodeCommand.java, src/main/java/cn/nukkit/command/defaults/DifficultyCommand.java, src/main/java/cn/nukkit/command/defaults/EffectCommand.java, src/main/java/cn/nukkit/command/defaults/EnchantCommand.java, src/main/java/cn/nukkit/command/defaults/GamemodeCommand.java, src/main/java/cn/nukkit/command/defaults/GiveCommand.java
This commit introduces two new fields to ArgType called stringenum : enum_values (you can predefine which strings can be used by player) and enum_type (blockList, itemList... so MCPE will automatically display list of all supported blocks, items)
Screenshots:
Example of usage in plugin:
=> Make using commands easier for players

src/main/java/cn/nukkit/item/Item.java, src/main/java/cn/nukkit/item/enchantment/Enchantment.java
Fixes the following error which stops a item with a incorrect enchantment from working.
`[ALERT] java.lang.NullPointerException at cn.nukkit.item.enchantment.Enchantment.getEnchantment(Enchantment.java:96) at cn.nukkit.item.Item.getEnchantments(Item.java:1710) at cn.nukkit.Player.handleDataPacket(Player.java:2752) at cn.nukkit.network.Network.processPackets(Network.java:185) at cn.nukkit.network.Network.processBatch(Network.java:156) at cn.nukkit.Player.handleDataPacket(Player.java:1895) at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:155) at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:123) at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:66) at cn.nukkit.network.Network.processInterfaces(Network.java:76) at …
=> Fixes Enchanted Item NullPointerException Error

pom.xml, src/main/java/cn/nukkit/command/defaults/TimeCommand.java, src/main/java/cn/nukkit/level/Level.java
####Fixed arg type of TimeCommand
**Here are time transformation codes:**  
int value;  
if ("day".equals(args[1])) {  
&nbsp;&nbsp;&nbsp;&nbsp;value = Level.TIME_DAY;  
} else if ("night".equals(args[1])) {  
&nbsp;&nbsp;&nbsp;&nbsp;value = Level.TIME_NIGHT;  
}  
**But the command parameters set that:**  
this.commandParameters.put("2args", new CommandParameter[]{  
&nbsp;&nbsp;&nbsp;&nbsp;new CommandParameter("add|set", CommandParameter.ARG_TYPE_STRING, false),  
&nbsp;&nbsp;&nbsp;&nbsp;new CommandParameter("value", CommandParameter.ARG_TYPE_INT, false)  
});  
**Arg 2 is int. So transformation does not work.  
And I just added String arg type:**  
this.commandParameters.put("2args_", new CommandParameter[]{  
&nbsp;&nbsp;&nbsp;&nbsp;new CommandParameter("add|set", …
=> Fixed arg type of TimeCommand

src/main/java/cn/nukkit/block/BlockFarmland.java, src/main/java/cn/nukkit/block/BlockWaterStill.java
Farmland is hydrated how it is described in Minecraft Wiki (http://minecraft.gamepedia.com/Farmland):
"A farmland block will be created dry. It will become hydrated if the following conditions are met:
1) Water up to four blocks away horizontally, including diagonals.
2) The water must be on the same level or 1 block above farmland block level."
Allow scheduled update for BlockWaterStill. 
This is made because water should be flowed into the BlockAir or any other BlockFlowable. For example, when sheduled update for BlockWaterStill is not allowed, if you set a Dirt block instead of BlockWaterStill (underwater) and then break this block, the water will not flow into the empty space. Also, a torch setted on BlockWaterStill's place will not be washed out without sheduled update.
=> Fixed Farmland and BlockWaterStill

src/main/java/cn/nukkit/Player.java, src/main/java/cn/nukkit/level/Level.java, src/main/java/cn/nukkit/network/protocol/SetSpawnPositionPacket.java
There were 2 uknown fields in SetSpawnPositionPacket. One of them, the VarInt (not UnsignedVarInt) one meant spawn type (player or world).
Now, when player switches world, or /setworldspawn command gets called, position compass is pointing to gets updated also (so the compass serves purpose now).
=> Compass position is updating now

pom.xml, src/main/java/cn/nukkit/item/Item.java, src/main/java/cn/nukkit/utils/BinaryStream.java, src/main/java/cn/nukkit/utils/VarInt.java, src/test/java/cn/nukkit/test/AngleTest.java, src/test/java/cn/nukkit/test/ClientChainDataTest.java, src/test/java/cn/nukkit/test/VarIntTest.java
The purpose of this PR is to enhance the efficiency of VarInt under huge network I/O. Nukkit have uses BigInteger to store VarInt values, but created large amounts of instances of BigInteger , which consumes up almost all the heap memory - that is 2.47 GiB or nearly 500 MiB per second for tested server under 1Gbps network I/O and hundreds of players, where JVM have to do the GC almost every 5 seconds and cause 200 ms of pauses each to reduce memory usage. 
By using enhanced VarInt, no instances of BigInteger is created. Less memory is now used by Nukkit network engines :)
=> Unit testing & Enhanced VarInt

src/main/java/cn/nukkit/utils/Zlib.java, src/test/java/cn/nukkit/test/VarIntTest.java, src/test/java/cn/nukkit/test/ZlibTest.java
We have reduced memory usage by enhanced VarInt in parse 1 (https://github.com/Nukkit/Nukkit/pull/1776).
Zlib is eating more and more memory as well. That is caused by creating too much instances by the deflater and inflater. Doing enhancements :)
Also see https://github.com/Nukkit/Nukkit/issues/1789.
Tests have done for commit on "Reduce byte array creation". In each test round, one player joins the server, stay for 30 seconds, then run to the horizon for 30 seconds, then quit the game. *Controlled group using software before this PR, experimental group using software after "Small improvement for Zlib"*. After 5 test round each group, *450 MiB (max VM submit) and 310 MiB (max VM consume) of memory is used by controlled group*, while *300 MiB (max VM submit) and 240 MiB (max VM consume) …
=> Reduce memory usage, phase 2 (Zlib)

src/main/java/cn/nukkit/entity/projectile/EntityArrow.java, src/main/java/cn/nukkit/entity/projectile/EntityProjectile.java
This change fixes Issue #1795 
It changes the damage logic to allow base damage to be overridden on a per-projectile basis, defaulting to zero (no damage).  Only arrow overrides this, so only arrows cause damage.
I reused the old projectile damage amount of 2, now just for arrows.
I have tested by shooting arrows and snowballs straight up into the air in survival mode.  Arrows still cause damage when they fall, but snowballs no longer do.
Let me know how it looks, this is my first Nukkit commit so I could easily have missed something.
=> Fix for Issue #1795: Non-Arrow projectiles shouldn't cause damage

src/main/java/cn/nukkit/utils/Zlib.java
This rolls back a change to Zlib.java which caused infrequent lockups of the main thread.  While infrequent, on a public server it was pretty serious when it happened since commands can't be entered on the console and no new users can log in.
Since the old code being restored created new object frequently, expect more frequent garbage collection if you have been using builds from the past 2-3 weeks.
=> Fix for issue #1817 -- main thread stuck (rollback Zlib)

src/main/java/cn/nukkit/inventory/PlayerInventory.java
PlayerInventory#setArmorContents can only change chestplate because of a bug in `for (int i = 0; i < 4; ++i) `:
`this.setItem(this.getSize() + 1, items[i]);`
it should be written as:
`this.setItem(this.getSize() + i, items[i]);`
=> Fixed PlayerInventory#setArmorContents

src/main/java/cn/nukkit/Player.java
It's useless to send 2 times the TakeItemEntityPacket, because it is already sending it to every viewers of the entity which is the dropped item.
=> Fixed duplicate dropped item

src/main/java/cn/nukkit/command/Command.java
The function allowChangesFrom(CommandMap commandMap) should return true to change the this.commandMap when commandMap isn't null and different from the old commandMap
=> cn.nukkit.command.register can't change the commandMap!

src/main/java/cn/nukkit/level/Level.java
A leak in setChunk resulting this thing to came out:
```
17:00:17 [CRITICAL] Exception while async task 0 invoking onCompletion
java.util.ConcurrentModificationException
at java.util.HashMap$HashIterator.nextNode(HashMap.java:1437)
at java.util.HashMap$ValueIterator.next(HashMap.java:1466)
at cn.nukkit.level.Level.setChunk(Level.java:2376)
at cn.nukkit.level.Level.generateChunkCallback(Level.java:2321)
at cn.nukkit.level.generator.task.PopulationTask.onCompletion(PopulationTask.java:164)
at cn.nukkit.scheduler.AsyncTask.collectTask(AsyncTask.java:83)
at cn.nukkit.scheduler.ServerScheduler.mainThreadHeartbeat(ServerScheduler.java:301)
at cn.nukkit.Server.tick(Server.java:1004)
at cn.nukkit.Server.tickProcessor(Server.java:794)
at cn.nukkit.Server.start(Server.java:773)
at …
```
=> Fix issue when attempt to register block entity by plugin

src/main/java/cn/nukkit/math/Angle.java
The AngleTest will fail in specific regions where commas are used as decimal separator. Setting the locale explicitly will prevent the JVM from using region dependent formatting.
=> Make Angle region-independent
